---
- name: Install python and pip
  apt:
    name:
     - python3
     - python3-pip
     - python3-venv
    state: present
  become: yes

- name: Create virtual environment
  command: python3 -m venv /home/{{ iot_user }}/iot_env
  args:
    creates: /home/{{ iot_user }}/iot_env

- name: install required python packages
  pip:
    name: paho-mqtt
    virtualenv: /home/{{ iot_user }}/iot_env

- name: copy sensor script
  template:
    src: sensor.py.j2
    dest: /home/{{ iot_user }}/iot_env/sensor.py
    mode: '0755'

